### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by icasallas** [kmaterna/Elastic_stresses_py#14]
Hi 

**A) I just installed elastic_stresses and running the Example 1 (Command Line) I got the follow error:**

elastic_stresses_driver.py my_config.txt 
/home/lab/anaconda3/envs/elastic_py/bin/elastic_stresses_driver.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('Elastic-stresses-py==1.0.0', 'elastic_stresses_driver.py')

Welcome to a simple forward modeling tool for calculating elastic displacements and coulomb stresses. 
Configuring with the following Params:
  -Config file: my_config.txt 
  -Input file: M6.8_2014.inzero 
  -Disp_points_file: CA_GPS_ll.txt 
  -Outdir: Outputs/my_experiment/ 
  -Elastic moduli: 30000000000.000000, 30000000000.000000 
  -Poisson's ratio and Alpha: 0.250000, 0.666667
Reading source and receiver fault information from file M6.8_2014.inzero 
strike_slip fraction:  -0.9993908270190958  / 1.0
dip_slip fraction:  -0.03489949670250097  / 1.0
Reading displacement points from file CA_GPS_ll.txt 
--> Read 105 displacement points 
Number of total sources: 1
Number of point sources: 1
Beginning stress calculation.
Number of sources: 1 
Number of receivers: 1 
Coefficient of friction: 0.400000
Splitting 1 receiver faults into 100 subfaults each.
Computing synthetic grid of displacements
Number of disp_points: 105
Resolving stresses on receiver fault(s).
Writing file Outputs/my_experiment/used_config.txt 
Writing file Outputs/my_experiment/used_inputs.txt 
Writing Outputs/my_experiment/ll_disps.txt 
Min, Max disp_points east: -0.000494, 0.017964 m
Min, Max disp_points north: -0.004059, 0.001042 m
Writing Outputs/my_experiment/receiver_traces.txt
Writing Outputs/my_experiment/source_traces.txt
Writing outfile Outputs/my_experiment/subfaulted.inp 
plot [WARNING]: File tmp.txt is empty!
Reading aftershocks from file CA_aftershocks_2014.txt 
Writing file Outputs/my_experiment/stresses_full.txt 
Making plot of shear stress on receiver fault patches: Outputs/my_experiment/Stresses_shear.png. 
Qt: Session management error: None of the authentication protocols specified are supported
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/elastic_py/bin/elastic_stresses_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('Elastic-stresses-py==1.0.0', 'elastic_stresses_driver.py')
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/EGG-INFO/scripts/elastic_stresses_driver.py", line 37, in <module>
    drive_calculation(args.config);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/EGG-INFO/scripts/elastic_stresses_driver.py", line 31, in drive_calculation
    PyCoulomb.output_manager.produce_outputs(params, inputs, obs_disp_points, obs_strain_points, out_object);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/Elastic_stresses_py/PyCoulomb/output_manager.py", line 40, in produce_outputs
    stress_plot(params, out_object, 'shear');  # can give vmin, vmax here if desired.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/Elastic_stresses_py/PyCoulomb/output_manager.py", line 158, in stress_plot
    cb = plt.colorbar(custom_cmap);
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2326, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/anaconda3/envs/elastic_py/lib/python3.11/site-packages/matplotlib/figure.py", line 1285, in colorbar
    raise ValueError(
ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

**B) The same error also when ruuning Example 2 (Jupyter Notebook)**

Beginning stress calculation.
Number of sources: 1 
Number of receivers: 1 
Coefficient of friction: 0.400000
Splitting 1 receiver faults into 100 subfaults each.
Computing synthetic grid of displacements
Number of disp_points: 105
Resolving stresses on receiver fault(s).
Resolving stresses on a horizontal profile.
Writing file Outputs/my_experiment/used_config.txt 
Writing file Outputs/my_experiment/used_inputs.txt 
Writing Outputs/my_experiment/ll_disps.txt 
Min, Max disp_points east: -0.000301, 0.012441 m
Min, Max disp_points north: -0.002757, 0.000744 m
Writing Outputs/my_experiment/receiver_traces.txt
Writing Outputs/my_experiment/source_traces.txt
Writing outfile Outputs/my_experiment/subfaulted.inp 
Reading aftershocks from file CA_aftershocks_2014.txt 
Writing file Outputs/my_experiment/stresses_full.txt 
Making plot of shear stress on receiver fault patches: Outputs/my_experiment/Stresses_shear.png. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 2
      1 out_object = PyCoulomb.run_dc3d.do_stress_computation(default_params, default_inputs, obs_disp_points, ());  # compute
----> 2 PyCoulomb.output_manager.produce_outputs(default_params, default_inputs, obs_disp_points, (), out_object);  # output

File ~/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/Elastic_stresses_py/PyCoulomb/output_manager.py:40, in produce_outputs(params, inputs, obs_disp_points, obs_strain_points, out_object)
     35 fault_dict_list = fso.fault_slip_object.coulomb_fault_to_fault_object(out_object.receiver_object);
     36 fso.file_io.io_slippy.write_stress_results_slippy_format(fault_dict_list, out_object.receiver_shear,
     37                                                          out_object.receiver_normal,
     38                                                          out_object.receiver_coulomb,
     39                                                          params.outdir + 'stresses_full.txt');
---> 40 stress_plot(params, out_object, 'shear');  # can give vmin, vmax here if desired.
     41 stress_plot(params, out_object, 'normal');
     42 stress_plot(params, out_object, 'coulomb');

File ~/anaconda3/envs/elastic_py/lib/python3.11/site-packages/Elastic_stresses_py-1.0.0-py3.11.egg/Elastic_stresses_py/PyCoulomb/output_manager.py:158, in stress_plot(params, out_object, stress_type, vmin, vmax)
    155     plt.gca().add_patch(mypolygon);
    157 custom_cmap.set_array(np.arange(vmin, vmax, 100));
--> 158 cb = plt.colorbar(custom_cmap);
    159 cb.set_label('Kilopascals', fontsize=22);
    160 for label in cb.ax.yaxis.get_ticklabels():

File ~/anaconda3/envs/elastic_py/lib/python3.11/site-packages/matplotlib/pyplot.py:2326, in colorbar(mappable, cax, ax, **kwargs)
   2321     if mappable is None:
   2322         raise RuntimeError('No mappable was found to use for colorbar '
   2323                            'creation. First define a mappable such as '
   2324                            'an image (with imshow) or a contour set ('
   2325                            'with contourf).')
-> 2326 ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kwargs)
   2327 return ret

File ~/anaconda3/envs/elastic_py/lib/python3.11/site-packages/matplotlib/figure.py:1285, in FigureBase.colorbar(self, mappable, cax, ax, use_gridspec, **kwargs)
   1283 if cax is None:
   1284     if ax is None:
-> 1285         raise ValueError(
   1286             'Unable to determine Axes to steal space for Colorbar. '
   1287             'Either provide the *cax* argument to use as the Axes for '
   1288             'the Colorbar, provide the *ax* argument to steal space '
   1289             'from it, or add *mappable* to an Axes.')
   1290     fig = (  # Figure of first axes; logic copied from make_axes.
   1291         [*ax.flat] if isinstance(ax, np.ndarray)
   1292         else [*ax] if np.iterable(ax)
   1293         else [ax])[0].figure
   1294     current_ax = fig.gca()

ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

Thanks.

**Comment by kmaterna** [comment]
Hi,
Thank you for pointing this out!  I’ve never used this library on Python
3.11 before, and I suspect this is an API change within the plotting
library (looks like the color bar is to blame).  I don’t run into this
issue on Python 3.7 or 3.9.  Let me try to reproduce it and fix it, and
I’ll get back to you.  I really appreciate the bug report!

In the mean time, the calculation worked; the issue was just in plotting.
The text files with the output data are being printed properly.  If you
wanted, you could read the top few lines of output manager, comment the
problematic plots, successfully print all the txts, and start to work with
the text file outputs yourself.  Just remember that when you make source
code changes like commenting the broken plots, you need to run Python
setup.py install to get those changes to build.

**Comment by kmaterna** [comment]
Could you tell me what version of matplotlib you are running in your environment?

**Comment by icasallas** [comment]
the version of matplotlib is 3.8.1

By the way, I also ran elastic_stresses with python 3.9 and the error persists.

**Comment by kmaterna** [comment]
I found it -- an [upgraded colorbar()](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#changes-of-api-after-deprecation) call in matplotlib >= 3.8.  I fixed the colorbar calls and it works on matplotlib 3.8 on my machine.  Please pull it / setup.py install / run it again and see what happens?

**Comment by icasallas** [comment]
@kmaterna I pulled it and ran the example 2, however there are the follow issues:

* the result of the plot 'horizontal_profile_stresses.png' is strange.
* the plots 'Displacement_model_on_grid.png', 'Stresses_coulomb.png', 'Stresses_normal.png' and 'Stresses_shear.png', do not have colorbar. 
![horizontal_profile_stresses](https://github.com/kmaterna/Elastic_stresses_py/assets/65173360/a5d9d332-033d-4b48-b316-e6f3a9ca22c8)
![Displacement_model_on_grid](https://github.com/kmaterna/Elastic_stresses_py/assets/65173360/44747ae7-d0c5-4113-a77b-60c01b9bad03)
![Stresses_coulomb](https://github.com/kmaterna/Elastic_stresses_py/assets/65173360/bbbb0b9f-2938-4f6f-a6a0-960b16d9a504)
![Stresses_normal](https://github.com/kmaterna/Elastic_stresses_py/assets/65173360/ce91e7d1-3103-49b4-b97f-c7b14435db48)
![Stresses_shear](https://github.com/kmaterna/Elastic_stresses_py/assets/65173360/8b7d36e2-108d-4224-9278-213d839eb8ed)

**Comment by kmaterna** [comment]
@icasallas oh my!  I pushed another fix which works better on my machine.

**Comment by icasallas** [comment]
@kmaterna Yes, it is OK. Thanks for fix the issue.
