### ISSUE TITLE
`numpy.distutils` is needed to install okada_wrapper, but has kindly been deprecated, and removed for Python 3.12

### ISSUE THREAD

**Issue by alomax** [kmaterna/Elastic_stresses_py#15]
Hi Kathryn,

Sorry to bother you with this kind of issue, but breaking old (e.g. > 2 years?!) things regularly seems to be accepted procedure in the Python community! Not healthy for one-shot funded, scientific research, where we often want things to work ... decades later!

In any case, `numpy.distutils` is needed to install okada_wrapper, but has kindly been deprecated, and removed for Python 3.12 by the numpy folks:
[https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration)

Of course, I am now running:
```
(elastic_py) okada_wrapper> python --version
Python 3.12.0
```
so the install of okada_wrapper did not work.

I solved the problem by changing in `requirements.yml`
` - python>=3.9
`
to
` - python=3.9
`

But, for your information, with the original `requirements.yml` I got:

```
(elastic_py) > pip install okada_wrapper
Collecting okada_wrapper
  Downloading okada_wrapper-18.12.07.3.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kz/l0h82yzn5zn7s4pgk2q19yfc0000gn/T/pip-install-_t5xipwk/okada-wrapper_30ea4b9985724bd0971bc3eab82fd4fb/setup.py", line 1, in <module>
          from numpy.distutils.core import setup, Extension
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

And I tried installing directly from [https://github.com/tbenthompson/okada_wrapper](https://github.com/tbenthompson/okada_wrapper) but got the same error, of course.

If you eventually evolve your code requiring features in Python≥3.9 I suppose it may be more difficult or impossible to also install okada_wrapper???

Thanks,

Anthony

**Comment by tbenthompson** [comment]
Kathryn recruited me to look into this! It's not going to be a trivial migration because setuptools does not support Fortran compilation.

Documentation on this deprecation/migration is here: https://numpy.org/doc/stable/reference/distutils_status_migration.html#

![2023-12-01 16 28 32@2x](https://github.com/kmaterna/Elastic_stresses_py/assets/4241811/e7de6b6b-2f08-45bd-ae26-db5b1bb2b917)

My suggestion would be:
a) migrate the okada_wrapper build system to use scikit-build as recommended in the link above
b) stop using okada_wrapper and switch to constructing rectangular dislocations with two triangular dislocations using [cutde](https://github.com/tbenthompson/cutde).

**Comment by kmaterna** [comment]
@alomax Thank you for letting me know about this!  I haven't moved up to pythons that high yet, but it's reasonable to want the code to work on those versions eventually!  I was considering migrating each rectangular element to two triangular elements at some point... looks like this is a good push to do it.  I'll hopefully get a chance to after AGU.  Thank you for the detailed and compassionate bug report :)

**Comment by iceseismic** [comment]
Thanks for your great installation documentation-notes Kathryn  ! - installation was fine for me (after hitting the same issue as Anthony) when I set to python 3.9 in your requirements.yml .

**Comment by kmaterna** [comment]
@alomax @tbenthompson   just letting you know that I've migrated my master branch onto Ben's cutde okada code rather than okada_wrapper.  Woohoo!  Triangles underlying everything now.  It's faster too.  I got it running on a clean environment with Python 3.11 and no okada_wrapper installed.  The readme reflects the simpler install instructions.  I hope that helps in case you're still working with these.

**Comment by alomax** [comment]
@kmaterna Thanks very much for the information. I installed all without trouble and re-ran some calculations - the results look identical when plotted for a normal fault case but are different and clearly wrong for a right-lateral, strike slip source and receiver dipping 89.9 deg or 89.0 deg, but maybe OK for 80.0 deg dip. I opened an issue:

I also get this warning:
`/Applications/anaconda3/envs/elastic_py2/lib/python3.11/site-packages/cutde/coordinators.py:77: UserWarning: The obs_pts input array has Fortran ordering. Converting to C ordering. This may be expensive.
`
which may not be a problem.

**Comment by kmaterna** [comment]
@alomax darn.  It passed the Coulomb benchmark and the unit tests, but I probably should add a unit test with 90° dip because that's so often pathological, isn't it? Thanks for the issue. I'll check it out today and see if I can reproduce it.

**Comment by alomax** [comment]
I think I had trouble with 90.0 deg in the previous version, but 89.9 seemed to work and seemed close enough to 90.
I can verify more tomorrow or give additional information (late here).
Thanks
