### ISSUE TITLE
Conversion of longitude increment in Receiver_Horizontal_Profile get_receiver_profile() does not correct for latitude

### ISSUE THREAD

**Issue by alomax** [kmaterna/Elastic_stresses_py#17]
I am working on a sequence at high latitude (Alaska) and notices strong distortions in horizontal profile plots.
I decided this was due to not accounting for the convergence of longitude meridians with increasing latitude when converting the longitude increment in km to degrees.
Finally, I made the following changes in [PyCoulomb/inputs_object/io_intxt.py](https://github.com/kmaterna/Elastic_stresses_py/blob/master/PyCoulomb/inputs_object/io_intxt.py) staring at line 216:

From:
```
    lonpts = np.arange(startlon, endlon, inc / 111.00);
    latpts = np.arange(startlat, endlat, inc / 111.00);
```

To:
```
    #20231211 ALomax - Bug fix# lonpts = np.arange(startlon, endlon, inc / 111.00);
    #20231211 ALomax - Bug fix# latpts = np.arange(startlat, endlat, inc / 111.00);
    if True:
        # 20231211 ALomax - Bug fix
        nlonpts = (2.0 * length + 1.e-4) / inc
        nlatpts = (2.0 * width + 1.e-4) / inc
        lon_inc = (endlon - startlon) / float(nlonpts)
        lat_inc = (endlat - startlat) / float(nlatpts)
        lonpts = np.arange(startlon, endlon, lon_inc);
        latpts = np.arange(startlat, endlat, lat_inc);
        # END 20231211 ALomax
    X, Y = np.meshgrid(lonpts, latpts);
    #20231211 ALomax DEBUG
    print("DEBUG: get_receiver_profile: np.shape(X):", np.shape(X))
    # END 20231211 ALomax
```

This seems to work correctly, though perhaps not the most direct or elegant solution and the "if True" and DEBUG print can be removed eventually.

Thanks,
Anthony

**Comment by kmaterna** [comment]
Thank you very much!!  I like this solution and will take it right away as soon as we resolve the steeply-dipping-fault issue.  I just want the solutions to be easily comparable while we bug-bash.

**Comment by kmaterna** [comment]
Fixed with commit here:
[478451e](https://github.com/kmaterna/Elastic_stresses_py/commit/478451e37be3a997e7a92d71fccddedfba6ef984)
