### ISSUE TITLE
When I run the test script, it shows that attributeerror: 'list' object has no attribute 'lon'

### ISSUE THREAD

**Issue by dream81** [kmaterna/Elastic_stresses_py#6]

**Comment by kmaterna** [comment]
Hello, thank you for telling me about this issue.  I reproduced it and fixed it; it related to a change I made a few months ago, but accidentally left some of the functions using the old way.  Thank you!  

Pull again and let me know if it's still not working.  Just FYI, when I work with the code, I sometimes flip certain outputs on/off with comments in output_manager.produce_outputs().  (Not the greatest, but I haven't gotten around to making them config-params yet.)    So you might have to do that at the moment, if you want certain plots.

**Comment by dream81** [comment]
Thank you @kmaterna. When I pull again and it works properly.
