### ISSUE TITLE
Error when making vertical plot of coulomb stress on receiver fault patches:  gmt_truncate_cpt: z_high = 0.00987477 larger than highest z (0.00987477)

### ISSUE THREAD

**Issue by MAcosta-GitHub** [kmaterna/Elastic_stresses_py#7]
Hi @kmaterna, 
Thank you for the great code. 

I am having the following error when running my own dataset (which has the exact same formats as used in the example you provided). 

> Making vertical plot of coulomb stress on receiver fault patches: Outputs/Ridgecrest_M6.4/Stresses_cross_section_coulomb.eps. 
> colorbar [ERROR]: gmt_truncate_cpt: z_high = 0.00987477 larger than highest z (0.00987477)

When running the example I do not get this error. 
Do you know where this can come from? 

Best, 
Mateo 

The full terminal output for the error is as follows: 

>  Making vertical plot of coulomb stress on receiver fault patches: Outputs/Ridgecrest_M6.4/Stresses_cross_section_coulomb.eps. 
> colorbar [ERROR]: gmt_truncate_cpt: z_high = 0.00987477 larger than highest z (0.00987477)
> Traceback (most recent call last):
>   File "/Users/acosta/Coulomb_materna/Elastic_stresses_py/PyCoulomb/bin/elastic_stresses_driver.py", line 37, in <module>
>     drive_calculation(args.config);
>   File "/Users/acosta/Coulomb_materna/Elastic_stresses_py/PyCoulomb/bin/elastic_stresses_driver.py", line 31, in drive_calculation
>     PyCoulomb.output_manager.produce_outputs(params, inputs, obs_disp_points, obs_strain_points, out_object);
>   File "/Users/acosta/Coulomb_materna/Elastic_stresses_py/PyCoulomb/output_manager.py", line 29, in produce_outputs
>     pygmt_plots.map_displacement_vectors(params, inputs, obs_disp_points, out_object, params.outdir+"vector_plot.png")
>   File "/Users/acosta/Coulomb_materna/Elastic_stresses_py/PyCoulomb/pygmt_plots.py", line 216, in map_displacement_vectors
>     fig.colorbar(position="JCR+w4.0i+v+o0.7i/0i", cmap="mycpt.cpt", truncate=str(vmin)+"/"+str(vmax),
>   File "/Users/acosta/anaconda3/envs/Coulomb_materna/lib/python3.9/site-packages/pygmt/helpers/decorators.py", line 582, in new_module
>     return module_func(*args, **kwargs)
>   File "/Users/acosta/anaconda3/envs/Coulomb_materna/lib/python3.9/site-packages/pygmt/helpers/decorators.py", line 725, in new_module
>     return module_func(*args, **kwargs)
>   File "/Users/acosta/anaconda3/envs/Coulomb_materna/lib/python3.9/site-packages/pygmt/src/colorbar.py", line 110, in colorbar
>     lib.call_module("colorbar", build_arg_string(kwargs))
>   File "/Users/acosta/anaconda3/envs/Coulomb_materna/lib/python3.9/site-packages/pygmt/clib/session.py", line 505, in call_module
>     raise GMTCLibError(
> pygmt.exceptions.GMTCLibError: Module 'colorbar' failed with status code 1:
> colorbar [ERROR]: gmt_truncate_cpt: z_high = 0.00987477 larger than highest z (0.00987477)

**Comment by kmaterna** [comment]
Hi @MAcosta-GitHub.  thanks for letting me know.  I have been getting this exact same error myself on a few plots in the last few weeks.  It's an interaction between "gmt makecpt -Tlow/high" and "gmt colorbar -Glow/high", especially when the range of values being plotted is really small or the values themselves are really small.  I haven't had a chance to fix it for real yet.    Thanks for the nudge - I'll let you know when I've pushed a fix!

**Comment by MAcosta-GitHub** [comment]
Hi @kmaterna Thank you very much for the fast answer. I'll try to look at the problem too and let you know if I can come up with something.  
thanks!

**Comment by kmaterna** [comment]
@MAcosta-GitHub I added a new commit - check it out and see what happens.   Please also tell me the result.  And feel free to send in PRs if you can easily fix it from this starting point.  This commit runs well on my data, but right now I'm not testing the exact same function that you're using, so I want to see the result.    
You can also see the implementation, in the file called 'utilities.py'.    ...slightly messy, but I think automatic handling of colorscales on the fly is never going to be pretty... 
https://github.com/kmaterna/Elastic_stresses_py/commit/d4962da8c7ec8367ed04a9e7186aa9893696327c

**Comment by MAcosta-GitHub** [comment]
@kmaterna the new commit works great thanks! 
I totally understand that automatic colorbars can be a mess. but I guess the patch works well for now.
I'll let you know if something comes up.

**Comment by MAcosta-GitHub** [comment]
Thank you for your reply. No, actually I had not been able to plot the map of Coulomb Stress for a given orientation. Is there a stray forward way of doing this? Otherwise I’ll dig deeper in the code to plot the maps. 

Best,
Mateo

**Comment by kmaterna** [comment]
@MAcosta-GitHub if you're using this for something official, just pull the Elastic_stresses_py code again.  I benchmarked a test case against Coulomb two days ago and reproduced the numbers exactly, but I fixed two small things in the process.  Always good to double-check.

**Comment by MAcosta-GitHub** [comment]
Hi @kmaterna ,

Thank you for the heads up! Ill pull again, and benchmark on my own too. 
Thanks!
